config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :comments, only: [:new, :create, :destroy]

  resource :cart, only: [:show, :update]
  delete 'cart/:item_id/remove', to: 'carts#destroy', as: 'destroy_cart_item'

  resources :products, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  # belongs_to :user
  before_create :generate_number

  belongs_to :user
  has_many :orderitems, dependent: :destroy
  has_many :products, through: :order_items

  def generate_number(size = 9)
    self.number ||= loop do
      random = random_candidate(size)
      break random unless self.class.exists?(number: random)
    end
  end

  def random_candidate(size = 9)
    "#{has_prefix}#{Array.new(size){rand(size)}.join}"
  end

  def has_prefix
    "BO"
  end

  def add_product(product_id, quantity)
    product = Product.find(product_id)
    if product
      orderitems.create(product_id: product.id, quantity: quantity, price: product.price)
      compute_total
    end
  end

  def compute_total
    sum = 0
    orderitems.each do |item|
      sum += item.price
    end
    update_attribute(:total, sum)
  end
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orderitems
  has_many :orders, through: :orderitems
  has_many :comments
  has_one_attached :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def current_order
              if current_user
                     order = Order.where(user_id: current_user.id).where(state: "created").last
                     if order.nil?
                            order = Order.create(user: current_user, state: "created")
                     end
                     return order
              end
              nil
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

       def update
              product = params[:cart][:product_id]
              quantity = params[:cart][:quantity]

              current_order.add_product(product, quantity)
              redirect_to root_path, notice: "El producto se añadió al carrito con éxito"
       end

       def show
              @order = current_order
       end

       def destroy
              @item = Orderitem.find(params[:item_id])

              @item.order.update(total: @item.order.total - @item.price)
              @item.destroy

              redirect_to cart_path, notice: "Haz eliminado el producto del carro"
       end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  

  def show
    @comments = Comment.new
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to dashboard_path, notice: "El producto fue creado con éxito" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to dashboard_path, notice: "El producto fue actualizado con éxito" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: "El producto fué eliminado con éxito" }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :product)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<div class="card mb-5 pb-5">
       <div class="card-body">
              <% @order.orderitems.includes(:product).each do |item| %>
                     <div class="row">
                            <div class="col-xs-2 col-md-2">

                                   <%= image_tag item.product.imagen, class: "ml-5 mt-3" %>
                            </div>
                            <div class="col-xs-4 col-md-6">
                                   <h4 class="product-name"><strong><%= item.product.name%></strong></h4><h4><small><%= item.product.description %></small></h4>
                                   <%= link_to '<h5 class="fas fa-trash-alt"></h5>'.html_safe, destroy_cart_item_path(item.id), method: :delete, class: "d-inline" %>
                            </div>
                            <div class="col-xs-6 col-md-4 row">
                                   <div class="col-xs-6 col-md-6 text-right"style="padding-top: 5px">
                                          <h6><strong><%= item.price%> <span class="text-muted">x</span></strong></h6>
                                   </div>
                            <div class="col-xs-4 col-md-4">
                                   <%= item.quantity %>
                            </div>
                            <div class="col-xs-2 col-md-2"></div>
                     </div>
              </div>
              <hr>
       <% end %>
       </div>
       <div class="card-footer">

              <div class="pull-right" style="margin: 5px">
              Total: $<b><%= @order.total %></b>
              </div>
       </div>
</div>

<%= link_to "Volver a la página principal", root_path, class: "btn btn-light" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketPg</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/footer" %>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<section class="banner">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%# <img src="market.png" class="d-block w-100" alt="banner1"> %>
      <%= image_tag "market.png", class:"d-block w-100" %>

    </div>
    <div class="carousel-item">
      <img src="https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60" class="d-block w-100" alt="banner2">
    </div>
    <div class="carousel-item">
      <img src="https://images.unsplash.com/photo-1563191911-e65f8655ebf9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDl8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60" class="d-block w-100" alt="banner3">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</section>
<!-- INFORMACION GENERAL DEL LOCAL -->
<section class="presentacion">
  <div class="row">
    <div class="col-6 info-pre">
      <h3 ><strong>Sobre el local</strong></h3>
      <p>Ofrecemos productos de tecnología con garantía.</p>
    </div>
    <div class="col-6 info-pre">
      <h3 ><strong>Sobre mi</strong></h3>
      <p>Seguridad garantizada.</p>
    </div>
  </div>

</section>

<section class="productos">

  <h1>Productos</h1>
  <ul class="cards">
  <% @products.each do |product| %>
      <li class="cards_item">
        <div class="card">
          <div class="card_image"><img src= <%=product.imagen %>></div>
          <div class="card_content">
            <h2 class="card_title"><%=product.name %></h2>

            <h1 >$<%=product.price %></h1>

            <div class="d-grid gap-2">
            <%= link_to "Read more", product_path(product), class: "btn btn-outline-light" %>
            </div>
          </div>
        </div>
      </li>
  <% end %>
  </ul>



</section>

app/views/products/show.html.erb
  <div class="container">
    <div class="p-0 my-5 d-flex justify-content-between bg-white row product-size" >
      <div class="container p-0 col-md-8">
        <%= image_tag @product.imagen, alt: "", class: "card-img-top product-show" %>
      </div>

      <div class="container p-5 col-md-4">
        <div>

          <h3> <strong> <%= @product.name %> </strong> </h3>
          <p class="text-secondary"><%= @product.description %></p>


        </div>
        <h2 class="card-trip-pricing py-4 m-0"> <strong> S/. <%= @product.price %> </strong></h2>
        <div>
        <% if user_signed_in? %>
                                   <%= form_for :cart, url: cart_path, method: :put do |f| %>
                                          <%= f.hidden_field :product_id, value: @product.id %>
                                          <%= f.hidden_field :quantity, value: 1 %>
                                          <%= f.submit "Añadir al carrito" , class: "d-grid gap-2 btn inline btn btn-success" %>
                                   <%end%>

        <% else %>
                                   <p class="buttoncart">Si deseas comprar primero debes loguearte</p>
                            <%end%>
        </div>



      </div>
    </div>
  </div>


  <div class="container">
    <h3>Comments</h3>
    <% if @product.comments.present? %>
      <% x = 1 %>
      <% @product.comments.each do |comment| %>
          <div class="bg-white p-4 border">
            <h6> <strong> Usuario <%= x %> </strong> </h6>
            <div class="card-title m-0"> <em>"<%= comment.text %>"</em> </div>

          </div>
          <% x += 1 %>
      <% end %>
    <% else %>
      <p>No hay reviews disponibles</p>
    <% end %>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Caren PG
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "marketlogo.png" %>

    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "<h5 class='fas fa-shopping-cart'></h5>".html_safe, cart_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown" style="margin: 5px">
            <%= image_tag "usuario.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

          </li>


        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>